// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attemptsForRun = `-- name: AttemptsForRun :many
SELECT run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result FROM attempt WHERE run_id = $1 ORDER BY started_at, attempt_no
`

func (q *Queries) AttemptsForRun(ctx context.Context, runID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, attemptsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.RunID,
			&i.Stage,
			&i.Turn,
			&i.AttemptNo,
			&i.Model,
			&i.Effort,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.Measured,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attemptsForStep = `-- name: AttemptsForStep :many
SELECT run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result FROM attempt WHERE run_id = $1 AND stage = $2 AND turn = $3 ORDER BY attempt_no
`

type AttemptsForStepParams struct {
	RunID pgtype.UUID
	Stage string
	Turn  int32
}

func (q *Queries) AttemptsForStep(ctx context.Context, arg AttemptsForStepParams) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, attemptsForStep, arg.RunID, arg.Stage, arg.Turn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attempt
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.RunID,
			&i.Stage,
			&i.Turn,
			&i.AttemptNo,
			&i.Model,
			&i.Effort,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.Measured,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endAttempt = `-- name: EndAttempt :one
UPDATE attempt SET ended_at = $5, result = $6
WHERE run_id = $1 AND stage = $2 AND turn = $3 AND attempt_no = $4
RETURNING run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result
`

type EndAttemptParams struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
	EndedAt   pgtype.Timestamptz
	Result    pgtype.Text
}

func (q *Queries) EndAttempt(ctx context.Context, arg EndAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, endAttempt,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.EndedAt,
		arg.Result,
	)
	var i Attempt
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.Model,
		&i.Effort,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.Measured,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const recordAttempt = `-- name: RecordAttempt :one
INSERT INTO attempt (
    run_id, stage, turn, attempt_no,
    model, effort,
    input_tokens, cached_input_tokens, output_tokens, reasoning_tokens,
    measured, started_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (run_id, stage, turn, attempt_no) DO UPDATE SET
    model = EXCLUDED.model,
    effort = EXCLUDED.effort,
    input_tokens = EXCLUDED.input_tokens,
    cached_input_tokens = EXCLUDED.cached_input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    reasoning_tokens = EXCLUDED.reasoning_tokens,
    measured = EXCLUDED.measured,
    started_at = EXCLUDED.started_at
RETURNING run_id, stage, turn, attempt_no, model, effort, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, measured, started_at, ended_at, result
`

type RecordAttemptParams struct {
	RunID             pgtype.UUID
	Stage             string
	Turn              int32
	AttemptNo         int32
	Model             string
	Effort            string
	InputTokens       int64
	CachedInputTokens int64
	OutputTokens      int64
	ReasoningTokens   int64
	Measured          bool
	StartedAt         pgtype.Timestamptz
}

// Idempotent: a retried call recording the same (run, stage, turn,
// attempt_no) again overwrites the row with the same values (an activity
// retry always carries what the first attempt did) rather than violating the
// primary key.
func (q *Queries) RecordAttempt(ctx context.Context, arg RecordAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, recordAttempt,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.Model,
		arg.Effort,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.Measured,
		arg.StartedAt,
	)
	var i Attempt
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.Model,
		&i.Effort,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.Measured,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}
