// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatcher_state.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dispatcherState = `-- name: DispatcherState :one
SELECT singleton, in_flight, written_at, config, config_error, breaker, candidates, free_slots FROM dispatcher_state WHERE singleton = TRUE
`

func (q *Queries) DispatcherState(ctx context.Context) (DispatcherState, error) {
	row := q.db.QueryRow(ctx, dispatcherState)
	var i DispatcherState
	err := row.Scan(
		&i.Singleton,
		&i.InFlight,
		&i.WrittenAt,
		&i.Config,
		&i.ConfigError,
		&i.Breaker,
		&i.Candidates,
		&i.FreeSlots,
	)
	return i, err
}

const putDispatcherState = `-- name: PutDispatcherState :exec
UPDATE dispatcher_state
SET config = $1,
    config_error = $2,
    breaker = $3,
    in_flight = $4,
    candidates = $5,
    free_slots = $6,
    written_at = $7
WHERE singleton = TRUE
`

type PutDispatcherStateParams struct {
	Config      []byte
	ConfigError string
	Breaker     []byte
	InFlight    []byte
	Candidates  []byte
	FreeSlots   int32
	WrittenAt   pgtype.Timestamptz
}

func (q *Queries) PutDispatcherState(ctx context.Context, arg PutDispatcherStateParams) error {
	_, err := q.db.Exec(ctx, putDispatcherState,
		arg.Config,
		arg.ConfigError,
		arg.Breaker,
		arg.InFlight,
		arg.Candidates,
		arg.FreeSlots,
		arg.WrittenAt,
	)
	return err
}
