// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration_probe.sql

package storedb

import (
	"context"
)

const migrationProbeExists = `-- name: MigrationProbeExists :one
SELECT EXISTS (
    SELECT FROM pg_catalog.pg_tables
    WHERE schemaname = 'public' AND tablename = 'migration_probe'
) AS exists
`

func (q *Queries) MigrationProbeExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, migrationProbeExists)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
