// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
	Model     string
	Effort    string
	// Includes cached_input_tokens.
	InputTokens       int64
	CachedInputTokens int64
	// Includes reasoning_tokens.
	OutputTokens    int64
	ReasoningTokens int64
	Measured        bool
	StartedAt       pgtype.Timestamptz
	EndedAt         pgtype.Timestamptz
	Result          pgtype.Text
}

type DispatcherState struct {
	Singleton   bool
	InFlight    []byte
	WrittenAt   pgtype.Timestamptz
	Config      []byte
	ConfigError string
	Breaker     []byte
	Candidates  []byte
	FreeSlots   int32
}

type MigrationProbe struct {
	Present bool
}

type Run struct {
	ID                pgtype.UUID
	TicketID          int64
	StartedAt         pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	Outcome           pgtype.Text
	FailureKind       string
	TargetOutcome     pgtype.Text
	TargetFailureKind string
	ReviewedHead      pgtype.Text
	MergeSha          pgtype.Text
}

type RunAgentAttempt struct {
	RunID                    pgtype.UUID
	StepOrdinal              int32
	AttemptNo                int32
	AgentStage               string
	Model                    string
	Effort                   string
	State                    string
	FailureKind              string
	ExecutionID              string
	UsageState               string
	InputTokens              int64
	CachedInputTokens        int64
	OutputTokens             int64
	ReasoningTokens          int64
	StartedAt                pgtype.Timestamptz
	EndedAt                  pgtype.Timestamptz
	Result                   []byte
	CheckpointCapabilityHash pgtype.Text
}

type RunAgentTranscript struct {
	RunID                 pgtype.UUID
	StepOrdinal           int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

type RunGitCheckpoint struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	Branch            string
	PushedHead        string
	ObservedBase      string
	PullRequestNumber int32
	PullRequestNodeID string
	StepResult        []byte
}

type RunRepositoryCapability struct {
	RunID          pgtype.UUID
	Generation     int64
	CapabilityHash string
}

type RunStep struct {
	RunID     pgtype.UUID
	Ordinal   int32
	Kind      string
	Iteration int32
	Reason    string
	State     string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	Result    []byte
}

type Step struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	CreatedAt pgtype.Timestamptz
}

type TargetHistoryStepMap struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	Ordinal   int32
	CreatedAt pgtype.Timestamptz
}

type Ticket struct {
	ID          int64
	Title       string
	Body        string
	State       string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ActiveRunID pgtype.UUID
}

type TicketEdge struct {
	BlockerTicketID int64
	BlockedTicketID int64
}

type Transcript struct {
	RunID                 pgtype.UUID
	Stage                 string
	Turn                  int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

type WebhookDelivery struct {
	DeliveryID string
	ReceivedAt pgtype.Timestamptz
}
