// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeLegacyRun = `-- name: CloseLegacyRun :one
UPDATE run SET ended_at = $2, outcome = 'failed', failure_kind = 'other'
WHERE id = $1
  AND ended_at IS NULL
  AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type CloseLegacyRunParams struct {
	ID      pgtype.UUID
	EndedAt pgtype.Timestamptz
}

func (q *Queries) CloseLegacyRun(ctx context.Context, arg CloseLegacyRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, closeLegacyRun, arg.ID, arg.EndedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const endRun = `-- name: EndRun :one
UPDATE run SET ended_at = $2, outcome = $3, failure_kind = $4
WHERE id = $1
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type EndRunParams struct {
	ID          pgtype.UUID
	EndedAt     pgtype.Timestamptz
	Outcome     pgtype.Text
	FailureKind string
}

func (q *Queries) EndRun(ctx context.Context, arg EndRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, endRun,
		arg.ID,
		arg.EndedAt,
		arg.Outcome,
		arg.FailureKind,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const openLegacyRuns = `-- name: OpenLegacyRuns :many
SELECT run.id, run.ticket_id, run.started_at, run.ended_at, run.outcome, run.failure_kind, run.target_outcome, run.target_failure_kind, run.reviewed_head, run.merge_sha FROM run
JOIN ticket ON ticket.id = run.ticket_id
WHERE run.ended_at IS NULL
  AND run.target_outcome IS NULL
  AND ticket.state IN ('working', 'review')
ORDER BY run.started_at, run.id
`

func (q *Queries) OpenLegacyRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.Query(ctx, openLegacyRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Outcome,
			&i.FailureKind,
			&i.TargetOutcome,
			&i.TargetFailureKind,
			&i.ReviewedHead,
			&i.MergeSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const run = `-- name: Run :one
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha FROM run WHERE id = $1
`

func (q *Queries) Run(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, run, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const runsForTicket = `-- name: RunsForTicket :many
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha FROM run WHERE ticket_id = $1 ORDER BY started_at DESC
`

// Most recent first: the console's ticket detail view leads with the
// current or latest Run.
func (q *Queries) RunsForTicket(ctx context.Context, ticketID int64) ([]Run, error) {
	rows, err := q.db.Query(ctx, runsForTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Outcome,
			&i.FailureKind,
			&i.TargetOutcome,
			&i.TargetFailureKind,
			&i.ReviewedHead,
			&i.MergeSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startRun = `-- name: StartRun :one
INSERT INTO run (id, ticket_id, started_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    ticket_id = EXCLUDED.ticket_id,
    started_at = EXCLUDED.started_at
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type StartRunParams struct {
	ID        pgtype.UUID
	TicketID  int64
	StartedAt pgtype.Timestamptz
}

// Idempotent: a retried call starting the same run id again overwrites the
// row with the same values (an activity retry always carries what the first
// attempt did) rather than violating the primary key.
func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, startRun, arg.ID, arg.TicketID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}
