// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: steps.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordStep = `-- name: RecordStep :exec
INSERT INTO step (run_id, stage, turn)
VALUES ($1, $2, $3)
ON CONFLICT (run_id, stage, turn) DO NOTHING
`

type RecordStepParams struct {
	RunID pgtype.UUID
	Stage string
	Turn  int32
}

// Idempotent: an activity retry recording the same step again is a no-op, not
// a constraint violation.
func (q *Queries) RecordStep(ctx context.Context, arg RecordStepParams) error {
	_, err := q.db.Exec(ctx, recordStep, arg.RunID, arg.Stage, arg.Turn)
	return err
}

const stepsForRun = `-- name: StepsForRun :many
SELECT run_id, stage, turn, created_at FROM step WHERE run_id = $1 ORDER BY created_at
`

func (q *Queries) StepsForRun(ctx context.Context, runID pgtype.UUID) ([]Step, error) {
	rows, err := q.db.Query(ctx, stepsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.RunID,
			&i.Stage,
			&i.Turn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
