// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket (title, body, state)
VALUES ($1, $2, $3)
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type CreateTicketParams struct {
	Title string
	Body  string
	State string
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket, arg.Title, arg.Body, arg.State)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const readyTickets = `-- name: ReadyTickets :many
SELECT t.id, t.title, t.body, t.state, t.created_at, t.updated_at, t.active_run_id FROM ticket t
WHERE t.state = 'open'
  AND NOT EXISTS (
    SELECT 1 FROM ticket_edge e
    JOIN ticket blocker ON blocker.id = e.blocker_ticket_id
    WHERE e.blocked_ticket_id = t.id AND blocker.state <> 'done'
  )
ORDER BY t.id
`

// A ticket is ready when it is open and every ticket it depends on is done.
// Direct dependencies only, per ADR-0012 -- a recursive CTE would answer a
// different question (transitive reachability) that nothing here asks.
func (q *Queries) ReadyTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, readyTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenLegacyTicket = `-- name: ReopenLegacyTicket :one
UPDATE ticket SET state = 'open', updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND state = $2
  AND updated_at = $3
  AND state IN ('working', 'review')
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type ReopenLegacyTicketParams struct {
	ID        int64
	State     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ReopenLegacyTicket(ctx context.Context, arg ReopenLegacyTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, reopenLegacyTicket, arg.ID, arg.State, arg.UpdatedAt)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const ticket = `-- name: Ticket :one
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE id = $1
`

func (q *Queries) Ticket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const tickets = `-- name: Tickets :many
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket ORDER BY id
`

func (q *Queries) Tickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, tickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketsByState = `-- name: TicketsByState :many
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE state = $1 ORDER BY id
`

func (q *Queries) TicketsByState(ctx context.Context, state string) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, ticketsByState, state)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActiveRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionTicketState = `-- name: TransitionTicketState :one
UPDATE ticket SET state = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = $2
  AND $3 <> 'active'
  AND state <> 'active'
  AND (state <> 'done' OR $3 = 'done')
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type TransitionTicketStateParams struct {
	ID      int64
	State   string
	State_2 string
}

func (q *Queries) TransitionTicketState(ctx context.Context, arg TransitionTicketStateParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, transitionTicketState, arg.ID, arg.State, arg.State_2)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const updateTicketState = `-- name: UpdateTicketState :one
UPDATE ticket SET state = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND state <> 'active'
  AND (state <> 'done' OR $2 = 'done')
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type UpdateTicketStateParams struct {
	ID    int64
	State string
}

func (q *Queries) UpdateTicketState(ctx context.Context, arg UpdateTicketStateParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketState, arg.ID, arg.State)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}
