// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const putTranscript = `-- name: PutTranscript :exec
INSERT INTO transcript (
    run_id, stage, turn, attempt_no,
    compressed_bytes, compression, uncompressed_size_bytes, checksum
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (run_id, stage, turn, attempt_no) DO NOTHING
`

type PutTranscriptParams struct {
	RunID                 pgtype.UUID
	Stage                 string
	Turn                  int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

// Idempotent: an activity retry persisting the same Attempt's transcript
// again is a no-op, not a constraint violation — the same reasoning as
// RecordStep's own ON CONFLICT DO NOTHING.
func (q *Queries) PutTranscript(ctx context.Context, arg PutTranscriptParams) error {
	_, err := q.db.Exec(ctx, putTranscript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
		arg.CompressedBytes,
		arg.Compression,
		arg.UncompressedSizeBytes,
		arg.Checksum,
	)
	return err
}

const transcript = `-- name: Transcript :one
SELECT run_id, stage, turn, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum FROM transcript
WHERE run_id = $1 AND stage = $2 AND turn = $3 AND attempt_no = $4
`

type TranscriptParams struct {
	RunID     pgtype.UUID
	Stage     string
	Turn      int32
	AttemptNo int32
}

func (q *Queries) Transcript(ctx context.Context, arg TranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, transcript,
		arg.RunID,
		arg.Stage,
		arg.Turn,
		arg.AttemptNo,
	)
	var i Transcript
	err := row.Scan(
		&i.RunID,
		&i.Stage,
		&i.Turn,
		&i.AttemptNo,
		&i.CompressedBytes,
		&i.Compression,
		&i.UncompressedSizeBytes,
		&i.Checksum,
	)
	return i, err
}

const transcriptKeysForRun = `-- name: TranscriptKeysForRun :many
SELECT stage, turn, attempt_no FROM transcript WHERE run_id = $1
`

type TranscriptKeysForRunRow struct {
	Stage     string
	Turn      int32
	AttemptNo int32
}

// The console's run detail view needs to know which Attempts have a
// transcript to download, without paying for every compressed blob just to
// render that flag.
func (q *Queries) TranscriptKeysForRun(ctx context.Context, runID pgtype.UUID) ([]TranscriptKeysForRunRow, error) {
	rows, err := q.db.Query(ctx, transcriptKeysForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscriptKeysForRunRow
	for rows.Next() {
		var i TranscriptKeysForRunRow
		if err := rows.Scan(&i.Stage, &i.Turn, &i.AttemptNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
