// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: v0.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateTargetTicket = `-- name: ActivateTargetTicket :one
UPDATE ticket SET state = 'active', active_run_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'open'
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type ActivateTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) ActivateTargetTicket(ctx context.Context, arg ActivateTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, activateTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const bindTargetAttemptCapability = `-- name: BindTargetAttemptCapability :one
UPDATE run_agent_attempt SET checkpoint_capability_hash = $4
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3 AND state = 'running'
  AND (checkpoint_capability_hash IS NULL OR checkpoint_capability_hash = $4)
  AND EXISTS (
      SELECT 1 FROM run
      JOIN ticket ON ticket.id = run.ticket_id
      WHERE run.id = $1 AND run.target_outcome IS NULL
        AND ticket.state = 'active' AND ticket.active_run_id = run.id
  )
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash
`

type BindTargetAttemptCapabilityParams struct {
	RunID                    pgtype.UUID
	StepOrdinal              int32
	AttemptNo                int32
	CheckpointCapabilityHash pgtype.Text
}

func (q *Queries) BindTargetAttemptCapability(ctx context.Context, arg BindTargetAttemptCapabilityParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, bindTargetAttemptCapability,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.CheckpointCapabilityHash,
	)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ExecutionID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const bindTargetRepositoryCapability = `-- name: BindTargetRepositoryCapability :one
INSERT INTO run_repository_capability (run_id, generation, capability_hash)
SELECT $1, $2, $3
WHERE EXISTS (
    SELECT 1 FROM run
    JOIN ticket ON ticket.id = run.ticket_id
    WHERE run.id = $1 AND run.target_outcome IS NULL
      AND ticket.state = 'active' AND ticket.active_run_id = run.id
)
ON CONFLICT (run_id) DO UPDATE SET
    generation = EXCLUDED.generation,
    capability_hash = EXCLUDED.capability_hash
WHERE run_repository_capability.generation < EXCLUDED.generation
   OR (run_repository_capability.generation = EXCLUDED.generation
       AND run_repository_capability.capability_hash = EXCLUDED.capability_hash)
RETURNING run_id, generation, capability_hash
`

type BindTargetRepositoryCapabilityParams struct {
	RunID          pgtype.UUID
	Generation     int64
	CapabilityHash string
}

func (q *Queries) BindTargetRepositoryCapability(ctx context.Context, arg BindTargetRepositoryCapabilityParams) (RunRepositoryCapability, error) {
	row := q.db.QueryRow(ctx, bindTargetRepositoryCapability, arg.RunID, arg.Generation, arg.CapabilityHash)
	var i RunRepositoryCapability
	err := row.Scan(&i.RunID, &i.Generation, &i.CapabilityHash)
	return i, err
}

const checkpointTargetAgentAttempt = `-- name: CheckpointTargetAgentAttempt :one
UPDATE run_agent_attempt SET
    execution_id = $4,
    state = $5,
    failure_kind = $6,
    usage_state = $7,
    input_tokens = $8,
    cached_input_tokens = $9,
    output_tokens = $10,
    reasoning_tokens = $11,
    ended_at = $12,
    result = $13
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash
`

type CheckpointTargetAgentAttemptParams struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	AttemptNo         int32
	ExecutionID       string
	State             string
	FailureKind       string
	UsageState        string
	InputTokens       int64
	CachedInputTokens int64
	OutputTokens      int64
	ReasoningTokens   int64
	EndedAt           pgtype.Timestamptz
	Result            []byte
}

func (q *Queries) CheckpointTargetAgentAttempt(ctx context.Context, arg CheckpointTargetAgentAttemptParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, checkpointTargetAgentAttempt,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.ExecutionID,
		arg.State,
		arg.FailureKind,
		arg.UsageState,
		arg.InputTokens,
		arg.CachedInputTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.EndedAt,
		arg.Result,
	)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ExecutionID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const completeCanceledTargetTicket = `-- name: CompleteCanceledTargetTicket :one
UPDATE ticket SET state = 'done', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'open' AND active_run_id IS NULL
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

func (q *Queries) CompleteCanceledTargetTicket(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, completeCanceledTargetTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const completeTargetMergeStep = `-- name: CompleteTargetMergeStep :one
UPDATE run_step SET state = 'completed', ended_at = $3, result = $4
WHERE run_id = $1 AND ordinal = $2 AND kind = 'merge_pull_request'
  AND (state = 'running' OR (state = 'completed' AND result = $4))
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type CompleteTargetMergeStepParams struct {
	RunID   pgtype.UUID
	Ordinal int32
	EndedAt pgtype.Timestamptz
	Result  []byte
}

func (q *Queries) CompleteTargetMergeStep(ctx context.Context, arg CompleteTargetMergeStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, completeTargetMergeStep,
		arg.RunID,
		arg.Ordinal,
		arg.EndedAt,
		arg.Result,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const completeTargetRunCanceled = `-- name: CompleteTargetRunCanceled :one
UPDATE run SET target_outcome = 'canceled', target_failure_kind = '', ended_at = $2
WHERE id = $1 AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type CompleteTargetRunCanceledParams struct {
	ID      pgtype.UUID
	EndedAt pgtype.Timestamptz
}

func (q *Queries) CompleteTargetRunCanceled(ctx context.Context, arg CompleteTargetRunCanceledParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeTargetRunCanceled, arg.ID, arg.EndedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const completeTargetRunSuccess = `-- name: CompleteTargetRunSuccess :one
UPDATE run SET target_outcome = 'succeeded', target_failure_kind = '',
    reviewed_head = $2, merge_sha = $3, ended_at = $4
WHERE id = $1 AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type CompleteTargetRunSuccessParams struct {
	ID           pgtype.UUID
	ReviewedHead pgtype.Text
	MergeSha     pgtype.Text
	EndedAt      pgtype.Timestamptz
}

func (q *Queries) CompleteTargetRunSuccess(ctx context.Context, arg CompleteTargetRunSuccessParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeTargetRunSuccess,
		arg.ID,
		arg.ReviewedHead,
		arg.MergeSha,
		arg.EndedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const completeTargetRunTerminal = `-- name: CompleteTargetRunTerminal :one
UPDATE run SET target_outcome = $2, target_failure_kind = $3, ended_at = $4
WHERE id = $1 AND target_outcome IS NULL
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type CompleteTargetRunTerminalParams struct {
	ID                pgtype.UUID
	TargetOutcome     pgtype.Text
	TargetFailureKind string
	EndedAt           pgtype.Timestamptz
}

func (q *Queries) CompleteTargetRunTerminal(ctx context.Context, arg CompleteTargetRunTerminalParams) (Run, error) {
	row := q.db.QueryRow(ctx, completeTargetRunTerminal,
		arg.ID,
		arg.TargetOutcome,
		arg.TargetFailureKind,
		arg.EndedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const completeTargetStep = `-- name: CompleteTargetStep :one
UPDATE run_step SET
    state = 'completed',
    ended_at = CASE WHEN run_step.state = 'running' THEN $3 ELSE run_step.ended_at END,
    result = CASE WHEN run_step.state = 'running' THEN $4 ELSE run_step.result END
WHERE run_id = $1 AND ordinal = $2
  AND EXISTS (
      SELECT 1 FROM run
      JOIN ticket ON ticket.id = run.ticket_id
      WHERE run.id = $1 AND run.target_outcome IS NULL
        AND ticket.state = 'active' AND ticket.active_run_id = run.id
  )
  AND (state = 'running' OR (state = 'completed' AND result = $4))
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type CompleteTargetStepParams struct {
	RunID   pgtype.UUID
	Ordinal int32
	EndedAt pgtype.Timestamptz
	Result  []byte
}

func (q *Queries) CompleteTargetStep(ctx context.Context, arg CompleteTargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, completeTargetStep,
		arg.RunID,
		arg.Ordinal,
		arg.EndedAt,
		arg.Result,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const completeTargetTicket = `-- name: CompleteTargetTicket :one
UPDATE ticket SET state = 'done', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'active' AND active_run_id = $2
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type CompleteTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) CompleteTargetTicket(ctx context.Context, arg CompleteTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, completeTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const countLegacyTicketStates = `-- name: CountLegacyTicketStates :one
SELECT COUNT(*) FROM ticket WHERE state IN ('working', 'review')
`

func (q *Queries) CountLegacyTicketStates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLegacyTicketStates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failRunningTargetAgentAttempts = `-- name: FailRunningTargetAgentAttempts :many
UPDATE run_agent_attempt SET state = 'failed', failure_kind = $3, ended_at = $4
WHERE run_id = $1 AND step_ordinal = $2 AND state = 'running'
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash
`

type FailRunningTargetAgentAttemptsParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	FailureKind string
	EndedAt     pgtype.Timestamptz
}

func (q *Queries) FailRunningTargetAgentAttempts(ctx context.Context, arg FailRunningTargetAgentAttemptsParams) ([]RunAgentAttempt, error) {
	rows, err := q.db.Query(ctx, failRunningTargetAgentAttempts,
		arg.RunID,
		arg.StepOrdinal,
		arg.FailureKind,
		arg.EndedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunAgentAttempt
	for rows.Next() {
		var i RunAgentAttempt
		if err := rows.Scan(
			&i.RunID,
			&i.StepOrdinal,
			&i.AttemptNo,
			&i.AgentStage,
			&i.Model,
			&i.Effort,
			&i.State,
			&i.FailureKind,
			&i.ExecutionID,
			&i.UsageState,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
			&i.CheckpointCapabilityHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failTargetStep = `-- name: FailTargetStep :one
UPDATE run_step SET state = 'failed', ended_at = $3, result = $4
WHERE run_id = $1 AND ordinal = $2 AND state = 'running'
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type FailTargetStepParams struct {
	RunID   pgtype.UUID
	Ordinal int32
	EndedAt pgtype.Timestamptz
	Result  []byte
}

func (q *Queries) FailTargetStep(ctx context.Context, arg FailTargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, failTargetStep,
		arg.RunID,
		arg.Ordinal,
		arg.EndedAt,
		arg.Result,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const failTargetTicket = `-- name: FailTargetTicket :one
UPDATE ticket SET state = 'failed', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'active' AND active_run_id = $2
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type FailTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) FailTargetTicket(ctx context.Context, arg FailTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, failTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const insertTargetRun = `-- name: InsertTargetRun :one
INSERT INTO run (id, ticket_id, started_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET id = run.id
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type InsertTargetRunParams struct {
	ID        pgtype.UUID
	TicketID  int64
	StartedAt pgtype.Timestamptz
}

func (q *Queries) InsertTargetRun(ctx context.Context, arg InsertTargetRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, insertTargetRun, arg.ID, arg.TicketID, arg.StartedAt)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const latestCanceledRunGitCheckpoint = `-- name: LatestCanceledRunGitCheckpoint :one
SELECT checkpoint.run_id, checkpoint.step_ordinal, checkpoint.branch, checkpoint.pushed_head, checkpoint.observed_base, checkpoint.pull_request_number, checkpoint.pull_request_node_id, checkpoint.step_result, COALESCE(merge_step.ordinal, 0)::integer AS merge_step_ordinal
FROM run AS predecessor
JOIN run_git_checkpoint AS checkpoint ON checkpoint.run_id = predecessor.id
LEFT JOIN run_step AS merge_step
  ON merge_step.run_id = predecessor.id
  AND merge_step.kind = 'merge_pull_request'
  AND merge_step.state = 'running'
WHERE predecessor.ticket_id = $1
  AND predecessor.id <> $2
  AND predecessor.target_outcome = 'canceled'
  AND checkpoint.pushed_head <> ''
ORDER BY predecessor.ended_at DESC, checkpoint.step_ordinal DESC
LIMIT 1
`

type LatestCanceledRunGitCheckpointParams struct {
	TicketID int64
	ID       pgtype.UUID
}

type LatestCanceledRunGitCheckpointRow struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	Branch            string
	PushedHead        string
	ObservedBase      string
	PullRequestNumber int32
	PullRequestNodeID string
	StepResult        []byte
	MergeStepOrdinal  int32
}

func (q *Queries) LatestCanceledRunGitCheckpoint(ctx context.Context, arg LatestCanceledRunGitCheckpointParams) (LatestCanceledRunGitCheckpointRow, error) {
	row := q.db.QueryRow(ctx, latestCanceledRunGitCheckpoint, arg.TicketID, arg.ID)
	var i LatestCanceledRunGitCheckpointRow
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.Branch,
		&i.PushedHead,
		&i.ObservedBase,
		&i.PullRequestNumber,
		&i.PullRequestNodeID,
		&i.StepResult,
		&i.MergeStepOrdinal,
	)
	return i, err
}

const putTargetAgentTranscript = `-- name: PutTargetAgentTranscript :exec
INSERT INTO run_agent_transcript (
    run_id, step_ordinal, attempt_no, compressed_bytes, compression,
    uncompressed_size_bytes, checksum
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (run_id, step_ordinal, attempt_no) DO UPDATE SET
    compressed_bytes = EXCLUDED.compressed_bytes,
    compression = EXCLUDED.compression,
    uncompressed_size_bytes = EXCLUDED.uncompressed_size_bytes,
    checksum = EXCLUDED.checksum
`

type PutTargetAgentTranscriptParams struct {
	RunID                 pgtype.UUID
	StepOrdinal           int32
	AttemptNo             int32
	CompressedBytes       []byte
	Compression           string
	UncompressedSizeBytes int64
	Checksum              []byte
}

func (q *Queries) PutTargetAgentTranscript(ctx context.Context, arg PutTargetAgentTranscriptParams) error {
	_, err := q.db.Exec(ctx, putTargetAgentTranscript,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.CompressedBytes,
		arg.Compression,
		arg.UncompressedSizeBytes,
		arg.Checksum,
	)
	return err
}

const putTargetGitCheckpoint = `-- name: PutTargetGitCheckpoint :one
INSERT INTO run_git_checkpoint (
    run_id, step_ordinal, branch, pushed_head, observed_base,
    pull_request_number, pull_request_node_id, step_result
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (run_id) DO UPDATE SET
    step_ordinal = EXCLUDED.step_ordinal,
    branch = EXCLUDED.branch,
    pushed_head = EXCLUDED.pushed_head,
    observed_base = EXCLUDED.observed_base,
    pull_request_number = EXCLUDED.pull_request_number,
    pull_request_node_id = EXCLUDED.pull_request_node_id,
    step_result = EXCLUDED.step_result
WHERE run_git_checkpoint.step_ordinal < EXCLUDED.step_ordinal
   OR (run_git_checkpoint.step_ordinal = EXCLUDED.step_ordinal
       AND run_git_checkpoint.branch = EXCLUDED.branch
       AND run_git_checkpoint.pushed_head = EXCLUDED.pushed_head
       AND run_git_checkpoint.observed_base = EXCLUDED.observed_base
       AND run_git_checkpoint.pull_request_number = EXCLUDED.pull_request_number
       AND run_git_checkpoint.pull_request_node_id = EXCLUDED.pull_request_node_id
       AND run_git_checkpoint.step_result = EXCLUDED.step_result)
RETURNING run_id, step_ordinal, branch, pushed_head, observed_base, pull_request_number, pull_request_node_id, step_result
`

type PutTargetGitCheckpointParams struct {
	RunID             pgtype.UUID
	StepOrdinal       int32
	Branch            string
	PushedHead        string
	ObservedBase      string
	PullRequestNumber int32
	PullRequestNodeID string
	StepResult        []byte
}

func (q *Queries) PutTargetGitCheckpoint(ctx context.Context, arg PutTargetGitCheckpointParams) (RunGitCheckpoint, error) {
	row := q.db.QueryRow(ctx, putTargetGitCheckpoint,
		arg.RunID,
		arg.StepOrdinal,
		arg.Branch,
		arg.PushedHead,
		arg.ObservedBase,
		arg.PullRequestNumber,
		arg.PullRequestNodeID,
		arg.StepResult,
	)
	var i RunGitCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.Branch,
		&i.PushedHead,
		&i.ObservedBase,
		&i.PullRequestNumber,
		&i.PullRequestNodeID,
		&i.StepResult,
	)
	return i, err
}

const reconcileCanceledTargetRunSuccess = `-- name: ReconcileCanceledTargetRunSuccess :one
UPDATE run SET target_outcome = 'succeeded', target_failure_kind = '',
    reviewed_head = $2, merge_sha = $3, ended_at = $4
WHERE id = $1 AND target_outcome = 'canceled'
RETURNING id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha
`

type ReconcileCanceledTargetRunSuccessParams struct {
	ID           pgtype.UUID
	ReviewedHead pgtype.Text
	MergeSha     pgtype.Text
	EndedAt      pgtype.Timestamptz
}

func (q *Queries) ReconcileCanceledTargetRunSuccess(ctx context.Context, arg ReconcileCanceledTargetRunSuccessParams) (Run, error) {
	row := q.db.QueryRow(ctx, reconcileCanceledTargetRunSuccess,
		arg.ID,
		arg.ReviewedHead,
		arg.MergeSha,
		arg.EndedAt,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const reopenTargetTicket = `-- name: ReopenTargetTicket :one
UPDATE ticket SET state = 'open', active_run_id = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND state = 'active' AND active_run_id = $2
RETURNING id, title, body, state, created_at, updated_at, active_run_id
`

type ReopenTargetTicketParams struct {
	ID          int64
	ActiveRunID pgtype.UUID
}

func (q *Queries) ReopenTargetTicket(ctx context.Context, arg ReopenTargetTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, reopenTargetTicket, arg.ID, arg.ActiveRunID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const startRecoveredTargetMergeStep = `-- name: StartRecoveredTargetMergeStep :one
INSERT INTO run_step (run_id, ordinal, kind, iteration, reason, state, started_at)
SELECT $1, COALESCE(MAX(ordinal), 0) + 1, 'merge_pull_request', 0,
       'reconcile confirmed external merge', 'running', $2
FROM run_step
WHERE run_id = $1
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type StartRecoveredTargetMergeStepParams struct {
	RunID     pgtype.UUID
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartRecoveredTargetMergeStep(ctx context.Context, arg StartRecoveredTargetMergeStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, startRecoveredTargetMergeStep, arg.RunID, arg.StartedAt)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const startTargetAgentAttempt = `-- name: StartTargetAgentAttempt :one
INSERT INTO run_agent_attempt (
    run_id, step_ordinal, attempt_no, agent_stage, model, effort, state,
    usage_state, started_at
) SELECT $1, $2, $3, $4, $5, $6, 'running', $7, $8
FROM run_step
WHERE run_id = $1 AND ordinal = $2 AND kind = $4 AND state = 'running'
  AND EXISTS (
      SELECT 1 FROM run
      JOIN ticket ON ticket.id = run.ticket_id
      WHERE run.id = $1 AND run.target_outcome IS NULL
        AND ticket.state = 'active' AND ticket.active_run_id = run.id
  )
ON CONFLICT (run_id, step_ordinal, attempt_no) DO UPDATE SET run_id = run_agent_attempt.run_id
WHERE run_agent_attempt.agent_stage = EXCLUDED.agent_stage
  AND run_agent_attempt.model = EXCLUDED.model
  AND run_agent_attempt.effort = EXCLUDED.effort
  AND run_agent_attempt.usage_state = EXCLUDED.usage_state
  AND run_agent_attempt.started_at = EXCLUDED.started_at
RETURNING run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash
`

type StartTargetAgentAttemptParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
	AgentStage  string
	Model       string
	Effort      string
	UsageState  string
	StartedAt   pgtype.Timestamptz
}

func (q *Queries) StartTargetAgentAttempt(ctx context.Context, arg StartTargetAgentAttemptParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, startTargetAgentAttempt,
		arg.RunID,
		arg.StepOrdinal,
		arg.AttemptNo,
		arg.AgentStage,
		arg.Model,
		arg.Effort,
		arg.UsageState,
		arg.StartedAt,
	)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ExecutionID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const startTargetStep = `-- name: StartTargetStep :one
INSERT INTO run_step (run_id, ordinal, kind, iteration, reason, state, started_at)
SELECT $1, $2, $3, $4, $5, 'running', $6
WHERE EXISTS (
    SELECT 1 FROM run
    JOIN ticket ON ticket.id = run.ticket_id
    WHERE run.id = $1 AND run.target_outcome IS NULL
      AND ticket.state = 'active' AND ticket.active_run_id = run.id
)
ON CONFLICT (run_id, ordinal) DO UPDATE SET run_id = run_step.run_id
WHERE run_step.kind = EXCLUDED.kind
  AND run_step.iteration = EXCLUDED.iteration
  AND run_step.reason = EXCLUDED.reason
  AND run_step.started_at = EXCLUDED.started_at
RETURNING run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result
`

type StartTargetStepParams struct {
	RunID     pgtype.UUID
	Ordinal   int32
	Kind      string
	Iteration int32
	Reason    string
	StartedAt pgtype.Timestamptz
}

func (q *Queries) StartTargetStep(ctx context.Context, arg StartTargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, startTargetStep,
		arg.RunID,
		arg.Ordinal,
		arg.Kind,
		arg.Iteration,
		arg.Reason,
		arg.StartedAt,
	)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const targetAgentAttempt = `-- name: TargetAgentAttempt :one
SELECT run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash FROM run_agent_attempt
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3
`

type TargetAgentAttemptParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetAgentAttempt(ctx context.Context, arg TargetAgentAttemptParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, targetAgentAttempt, arg.RunID, arg.StepOrdinal, arg.AttemptNo)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ExecutionID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const targetAgentAttemptForUpdate = `-- name: TargetAgentAttemptForUpdate :one
SELECT run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash FROM run_agent_attempt
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3 FOR UPDATE
`

type TargetAgentAttemptForUpdateParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetAgentAttemptForUpdate(ctx context.Context, arg TargetAgentAttemptForUpdateParams) (RunAgentAttempt, error) {
	row := q.db.QueryRow(ctx, targetAgentAttemptForUpdate, arg.RunID, arg.StepOrdinal, arg.AttemptNo)
	var i RunAgentAttempt
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.AgentStage,
		&i.Model,
		&i.Effort,
		&i.State,
		&i.FailureKind,
		&i.ExecutionID,
		&i.UsageState,
		&i.InputTokens,
		&i.CachedInputTokens,
		&i.OutputTokens,
		&i.ReasoningTokens,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
		&i.CheckpointCapabilityHash,
	)
	return i, err
}

const targetAgentAttemptsForRun = `-- name: TargetAgentAttemptsForRun :many
SELECT run_id, step_ordinal, attempt_no, agent_stage, model, effort, state, failure_kind, execution_id, usage_state, input_tokens, cached_input_tokens, output_tokens, reasoning_tokens, started_at, ended_at, result, checkpoint_capability_hash FROM run_agent_attempt WHERE run_id = $1 ORDER BY step_ordinal, attempt_no
`

func (q *Queries) TargetAgentAttemptsForRun(ctx context.Context, runID pgtype.UUID) ([]RunAgentAttempt, error) {
	rows, err := q.db.Query(ctx, targetAgentAttemptsForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunAgentAttempt
	for rows.Next() {
		var i RunAgentAttempt
		if err := rows.Scan(
			&i.RunID,
			&i.StepOrdinal,
			&i.AttemptNo,
			&i.AgentStage,
			&i.Model,
			&i.Effort,
			&i.State,
			&i.FailureKind,
			&i.ExecutionID,
			&i.UsageState,
			&i.InputTokens,
			&i.CachedInputTokens,
			&i.OutputTokens,
			&i.ReasoningTokens,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
			&i.CheckpointCapabilityHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetAgentTranscript = `-- name: TargetAgentTranscript :one
SELECT run_id, step_ordinal, attempt_no, compressed_bytes, compression, uncompressed_size_bytes, checksum FROM run_agent_transcript
WHERE run_id = $1 AND step_ordinal = $2 AND attempt_no = $3
`

type TargetAgentTranscriptParams struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetAgentTranscript(ctx context.Context, arg TargetAgentTranscriptParams) (RunAgentTranscript, error) {
	row := q.db.QueryRow(ctx, targetAgentTranscript, arg.RunID, arg.StepOrdinal, arg.AttemptNo)
	var i RunAgentTranscript
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.AttemptNo,
		&i.CompressedBytes,
		&i.Compression,
		&i.UncompressedSizeBytes,
		&i.Checksum,
	)
	return i, err
}

const targetGitCheckpoint = `-- name: TargetGitCheckpoint :one
SELECT run_id, step_ordinal, branch, pushed_head, observed_base, pull_request_number, pull_request_node_id, step_result FROM run_git_checkpoint WHERE run_id = $1
`

func (q *Queries) TargetGitCheckpoint(ctx context.Context, runID pgtype.UUID) (RunGitCheckpoint, error) {
	row := q.db.QueryRow(ctx, targetGitCheckpoint, runID)
	var i RunGitCheckpoint
	err := row.Scan(
		&i.RunID,
		&i.StepOrdinal,
		&i.Branch,
		&i.PushedHead,
		&i.ObservedBase,
		&i.PullRequestNumber,
		&i.PullRequestNodeID,
		&i.StepResult,
	)
	return i, err
}

const targetRepositoryCapabilityForUpdate = `-- name: TargetRepositoryCapabilityForUpdate :one
SELECT run_id, generation, capability_hash FROM run_repository_capability WHERE run_id = $1 FOR UPDATE
`

func (q *Queries) TargetRepositoryCapabilityForUpdate(ctx context.Context, runID pgtype.UUID) (RunRepositoryCapability, error) {
	row := q.db.QueryRow(ctx, targetRepositoryCapabilityForUpdate, runID)
	var i RunRepositoryCapability
	err := row.Scan(&i.RunID, &i.Generation, &i.CapabilityHash)
	return i, err
}

const targetRunForUpdate = `-- name: TargetRunForUpdate :one
SELECT id, ticket_id, started_at, ended_at, outcome, failure_kind, target_outcome, target_failure_kind, reviewed_head, merge_sha FROM run WHERE id = $1 FOR UPDATE
`

func (q *Queries) TargetRunForUpdate(ctx context.Context, id pgtype.UUID) (Run, error) {
	row := q.db.QueryRow(ctx, targetRunForUpdate, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Outcome,
		&i.FailureKind,
		&i.TargetOutcome,
		&i.TargetFailureKind,
		&i.ReviewedHead,
		&i.MergeSha,
	)
	return i, err
}

const targetRunOwned = `-- name: TargetRunOwned :one
SELECT EXISTS (
    SELECT 1 FROM run
    JOIN ticket ON ticket.id = run.ticket_id
    WHERE run.id = $1 AND run.target_outcome IS NULL
      AND ticket.state = 'active' AND ticket.active_run_id = run.id
)
`

func (q *Queries) TargetRunOwned(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, targetRunOwned, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const targetStep = `-- name: TargetStep :one
SELECT run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result FROM run_step WHERE run_id = $1 AND ordinal = $2
`

type TargetStepParams struct {
	RunID   pgtype.UUID
	Ordinal int32
}

func (q *Queries) TargetStep(ctx context.Context, arg TargetStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, targetStep, arg.RunID, arg.Ordinal)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const targetStepForRun = `-- name: TargetStepForRun :many
SELECT run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result FROM run_step WHERE run_id = $1 ORDER BY ordinal
`

func (q *Queries) TargetStepForRun(ctx context.Context, runID pgtype.UUID) ([]RunStep, error) {
	rows, err := q.db.Query(ctx, targetStepForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.RunID,
			&i.Ordinal,
			&i.Kind,
			&i.Iteration,
			&i.Reason,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetStepForUpdate = `-- name: TargetStepForUpdate :one
SELECT run_id, ordinal, kind, iteration, reason, state, started_at, ended_at, result FROM run_step WHERE run_id = $1 AND ordinal = $2 FOR UPDATE
`

type TargetStepForUpdateParams struct {
	RunID   pgtype.UUID
	Ordinal int32
}

func (q *Queries) TargetStepForUpdate(ctx context.Context, arg TargetStepForUpdateParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, targetStepForUpdate, arg.RunID, arg.Ordinal)
	var i RunStep
	err := row.Scan(
		&i.RunID,
		&i.Ordinal,
		&i.Kind,
		&i.Iteration,
		&i.Reason,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.Result,
	)
	return i, err
}

const targetTicketForUpdate = `-- name: TargetTicketForUpdate :one
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE id = $1 FOR UPDATE
`

func (q *Queries) TargetTicketForUpdate(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, targetTicketForUpdate, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}

const targetTranscriptKeysForRun = `-- name: TargetTranscriptKeysForRun :many
SELECT run_id, step_ordinal, attempt_no FROM run_agent_transcript
WHERE run_id = $1 ORDER BY step_ordinal, attempt_no
`

type TargetTranscriptKeysForRunRow struct {
	RunID       pgtype.UUID
	StepOrdinal int32
	AttemptNo   int32
}

func (q *Queries) TargetTranscriptKeysForRun(ctx context.Context, runID pgtype.UUID) ([]TargetTranscriptKeysForRunRow, error) {
	rows, err := q.db.Query(ctx, targetTranscriptKeysForRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TargetTranscriptKeysForRunRow
	for rows.Next() {
		var i TargetTranscriptKeysForRunRow
		if err := rows.Scan(&i.RunID, &i.StepOrdinal, &i.AttemptNo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketForTargetClaim = `-- name: TicketForTargetClaim :one
SELECT id, title, body, state, created_at, updated_at, active_run_id FROM ticket WHERE id = $1 FOR UPDATE
`

func (q *Queries) TicketForTargetClaim(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, ticketForTargetClaim, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActiveRunID,
	)
	return i, err
}
