// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package storedb

import (
	"context"
)

const recordWebhookDelivery = `-- name: RecordWebhookDelivery :one
INSERT INTO webhook_delivery (delivery_id)
VALUES ($1)
ON CONFLICT DO NOTHING
RETURNING delivery_id, received_at
`

// Records delivery_id as seen. Returns no row (pgx.ErrNoRows) when it was
// already recorded -- the caller's signal that this is a redelivery.
func (q *Queries) RecordWebhookDelivery(ctx context.Context, deliveryID string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, recordWebhookDelivery, deliveryID)
	var i WebhookDelivery
	err := row.Scan(&i.DeliveryID, &i.ReceivedAt)
	return i, err
}
