package work

import (
	"fmt"
	"strings"
	"time"

	"github.com/google/uuid"
)

// RunWorkerID identifies one concrete worker generation for a target Run.
type RunWorkerID string

// RunWorkerIdentity is the stable Run plus the replaceable worker generation.
// Generation starts at one and increases only after permanent worker loss.
type RunWorkerIdentity struct {
	RunID      string
	Generation int
}

// NewRunWorkerIdentity parses the durable Run and generation once at the
// boundary where a concrete worker generation is constructed.
func NewRunWorkerIdentity(runID string, generation int) (RunWorkerIdentity, error) {
	identity := RunWorkerIdentity{RunID: runID, Generation: generation}
	if err := identity.Validate(); err != nil {
		return RunWorkerIdentity{}, fmt.Errorf("constructing Run Worker identity: %w", err)
	}
	return identity, nil
}

// Validate rejects identities that cannot be embedded safely in Kubernetes and
// Temporal names. Run IDs are generated by Temporal; accepting only its
// lowercase UUID-shaped alphabet keeps target names deterministic and inert.
func (i RunWorkerIdentity) Validate() error {
	if i.Generation <= 0 {
		return fmt.Errorf("run worker identity needs a positive generation: %w", ErrInvalidRun)
	}
	parsed, err := uuid.Parse(i.RunID)
	if err != nil || parsed.String() != i.RunID {
		return fmt.Errorf("run worker Run ID %q is not a canonical UUID: %w", i.RunID, ErrInvalidRun)
	}
	if len(runWorkerName(i)) > 63 {
		return fmt.Errorf("run worker identity %q generation %d exceeds the Kubernetes name limit: %w", i.RunID, i.Generation, ErrInvalidRun)
	}
	return nil
}

const runWorkerTaskQueuePrefix = "software-factory-run-worker-"

// RunWorkerTaskQueue constructs the private queue for one validated generation.
func RunWorkerTaskQueue(identity RunWorkerIdentity) (string, error) {
	if err := identity.Validate(); err != nil {
		return "", fmt.Errorf("constructing Run Worker task queue: %w", err)
	}
	return fmt.Sprintf("%s%s-g%d", runWorkerTaskQueuePrefix, identity.RunID, identity.Generation), nil
}

// RunWorkerToolTaskQueue constructs the credential-free tool container queue
// for one validated generation. Repository activities stay on the base queue.
func RunWorkerToolTaskQueue(identity RunWorkerIdentity) (string, error) {
	base, err := RunWorkerTaskQueue(identity)
	if err != nil {
		return "", fmt.Errorf("constructing Run Worker tool task queue: %w", err)
	}
	return base + "-tools", nil
}

// RunWorkerName constructs the Kubernetes name for one validated generation.
func RunWorkerName(identity RunWorkerIdentity) (RunWorkerID, error) {
	if err := identity.Validate(); err != nil {
		return "", fmt.Errorf("constructing Run Worker name: %w", err)
	}
	return RunWorkerID(runWorkerName(identity)), nil
}

// ParseRunWorkerID accepts only the deterministic name of identity. Lifecycle
// operations derive this value from identity instead of accepting arbitrary
// pod names from workflow payloads.
func ParseRunWorkerID(raw string, identity RunWorkerIdentity) (RunWorkerID, error) {
	want, err := RunWorkerName(identity)
	if err != nil {
		return "", fmt.Errorf("parsing Run Worker ID: %w", err)
	}
	if RunWorkerID(raw) != want {
		return "", fmt.Errorf("run worker ID %q does not identify Run %q generation %d: %w", raw, identity.RunID, identity.Generation, ErrInvalidRun)
	}
	return want, nil
}

func runWorkerName(identity RunWorkerIdentity) string {
	return fmt.Sprintf("run-worker-%s-g%d", identity.RunID, identity.Generation)
}

// RunWorkerCredentialRevision is the complete safe result of installing a
// renewable credential. It may cross a Temporal activity boundary; the token
// itself may not.
type RunWorkerCredentialRevision struct {
	Revision  string
	ExpiresAt time.Time
}

// Validate reports whether the installed revision can be observed safely.
func (r RunWorkerCredentialRevision) Validate() error {
	if strings.TrimSpace(r.Revision) == "" {
		return fmt.Errorf("run worker credential revision is empty: %w", ErrInvalidRun)
	}
	if r.ExpiresAt.IsZero() {
		return fmt.Errorf("run worker credential expiry is empty: %w", ErrInvalidRun)
	}
	return nil
}

// RunWorkerSpec describes one target worker pod without carrying any secret.
type RunWorkerSpec struct {
	TicketNumber    int
	Identity        RunWorkerIdentity
	Image           string
	CPURequest      string
	MemoryLimit     string
	DeadlineSeconds int64
	Env             map[string]string
}

// NewRunWorkerSpec validates and snapshots one target generation's immutable
// pod inputs. Env is copied so a caller cannot mutate the requested generation
// after construction.
func NewRunWorkerSpec(spec RunWorkerSpec) (RunWorkerSpec, error) {
	if err := spec.Validate(); err != nil {
		return RunWorkerSpec{}, fmt.Errorf("constructing Run Worker spec: %w", err)
	}
	copy := spec
	copy.Env = make(map[string]string, len(spec.Env))
	for key, value := range spec.Env {
		copy.Env[key] = value
	}
	return copy, nil
}

// Validate rejects specs that cannot describe one bounded worker generation.
func (s RunWorkerSpec) Validate() error {
	if err := s.Identity.Validate(); err != nil {
		return fmt.Errorf("validating Run Worker spec identity: %w", err)
	}
	if s.TicketNumber <= 0 || s.DeadlineSeconds <= 0 {
		return fmt.Errorf("run worker spec needs a positive Ticket and deadline: %w", ErrInvalidRun)
	}
	if strings.TrimSpace(s.Image) == "" || strings.TrimSpace(s.CPURequest) == "" || strings.TrimSpace(s.MemoryLimit) == "" {
		return fmt.Errorf("run worker spec needs image and resource settings: %w", ErrInvalidRun)
	}
	if s.Env == nil {
		return fmt.Errorf("run worker spec needs an environment snapshot: %w", ErrInvalidRun)
	}
	return nil
}

// RunWorkerSecretMaterial is handed directly from the main-control activity to
// Kubernetes. Credential's JSON refusal prevents either value from entering
// Temporal history accidentally.
type RunWorkerSecretMaterial struct {
	GitHubToken          Credential
	GitHubLogin          string
	GitHubExpiresAt      time.Time
	CheckpointCapability Credential
}

// Published environment and projected-file paths shared by the provisioner,
// image, and Run Worker composition root. Secret values never have env names.
const (
	RunWorkerIDEnv                    = "RUN_WORKER_ID"
	RunWorkerRunIDEnv                 = "RUN_ID"
	RunWorkerGenerationEnv            = "RUN_WORKER_GENERATION"
	RunWorkerTaskQueueEnv             = "RUN_WORKER_TASK_QUEUE"
	RunWorkerTemporalHostPortEnv      = "TEMPORAL_HOST_PORT"
	RunWorkerTemporalNamespaceEnv     = "TEMPORAL_NAMESPACE"
	RunWorkerBlobsURLEnv              = "BLOBS_URL"
	RunWorkerMetricsAddrEnv           = "METRICS_ADDR"
	RunWorkerCheckpointAPIURLEnv      = "CHECKPOINT_API_URL"
	RunWorkerGitHubRepositoryEnv      = "GITHUB_REPOSITORY"
	RunWorkerGitHubCredentialDir      = "/var/run/secrets/software-factory/github"
	RunWorkerGitHubTokenFile          = RunWorkerGitHubCredentialDir + "/token"
	RunWorkerGitHubLoginFile          = RunWorkerGitHubCredentialDir + "/login"
	RunWorkerGitHubRevisionFile       = RunWorkerGitHubCredentialDir + "/revision"
	RunWorkerGitHubExpiresAtFile      = RunWorkerGitHubCredentialDir + "/expires-at"
	RunWorkerCheckpointCapabilityDir  = "/var/run/secrets/software-factory/checkpoint"
	RunWorkerCheckpointCapabilityFile = RunWorkerCheckpointCapabilityDir + "/capability"
	RunWorkerRepositoryCapabilityDir  = "/var/run/secrets/software-factory/repository-checkpoint"
	RunWorkerRepositoryCapabilityFile = RunWorkerRepositoryCapabilityDir + "/capability"
)

// Published environment names shared by the target pod renderer and the
// credential-free Tool Worker composition root. The queue name is explicit so
// the sidecar reads the exact generation-specific value rendered by the
// provisioner instead of reconstructing it independently.
const (
	ToolWorkerTaskQueueEnv         = "TOOL_WORKER_TASK_QUEUE"
	ToolWorkerTemporalHostPortEnv  = "TEMPORAL_HOST_PORT"
	ToolWorkerTemporalNamespaceEnv = "TEMPORAL_NAMESPACE"
	ToolWorkerBlobsURLEnv          = "BLOBS_URL"
)
